:backend = http://localhost:8000




# test CORS
OPTIONS :backend/api/secret-santa
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://localhost:3003
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: http://localhost:3003/



# Create secret santa
POST :backend/api/secret-santa
Content-Type: application/json
{ "info":
  { "eventName"    : "My Secret Santa"
  , "hostName"     : "Foo"
  , "hostEmail"    : "foo@bar"
  , "timeZone"     : "+0100"
  , "date"         : "2022-03-18"
  , "time"         : "13:26"
  , "location"     : null
  , "price"        : null
  , "description"  : "Some description"
  }
, "participants" :
  [ { "name" : "Brecht"
    , "email" : "brecht@host"
    }
  , { "name" : "Liesse"
    , "email" : "liesse@host"
    }
  , { "name" : "Lina"
    , "email" : "lina@host"
    }
  ]
}

# Get all secret santas
GET :backend/api/secret-santa